#!/usr/bin/env python

import sys, os
import pika
import json
import re
import socket

import logging
logging.basicConfig(level=logging.ERROR)

GIT_BASE="/home/git/repositories/"
SSH_URL_TEMPLATE="git@" + socket.getfqdn() + ":{0}.git"

RABBITMQ_HOST='localhost'
RABBITMQ_PORT=5672

if __name__ == '__main__':
    connection_params = pika.ConnectionParameters(host=RABBITMQ_HOST,
                                                  port=RABBITMQ_PORT)
    connection = pika.BlockingConnection(connection_params)
    channel = connection.channel()

    channel.exchange_declare(exchange='git', type='topic')

    repo_path = os.path.abspath(os.environ.get('GIT_DIR', '.'))
    m = re.match(r'^'+re.escape(GIT_BASE)+'(.*)\.git$', repo_path)
    if not m:
        raise Exception('GIT_DIR did not match pattern')
    repo_name = m.group(1)

    repository = {'full_name': repo_name,
                  'ssh_url': SSH_URL_TEMPLATE.format(repo_name)}

    for line in sys.stdin:
        before, after, ref = line.strip().split(' ', 2)
        doc = {'repository': repository, 'ref': ref,
               'before': before, 'after': after}
        channel.basic_publish(exchange='git',
                              routing_key=repo_name,
                              body=json.dumps(doc))

    connection.close()
